//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İcarePlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int Id { get; set; }
        public string description { get; set; }
        public string UrlImg { get; set; }
        public string header { get; set; }
        public string Icon { get; set; }
    }
}
