//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İcarePlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public string ContractType { get; set; }
        public string ContractLink { get; set; }
        public Nullable<int> EstateId { get; set; }
        public string RentalId { get; set; }
        public System.DateTime ContractDeadline { get; set; }
        public System.DateTime SignContract { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public decimal RentPrice { get; set; }
    
        public virtual Estate Estate { get; set; }
    }
}
