//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İcarePlatform
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstateSpesification
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Value { get; set; }
        public Nullable<int> EstateId { get; set; }
    
        public virtual Estate Estate { get; set; }
    }
}
